services:
    
    apipedidos: #Nome do serviço
        container_name: api-pedidos-springboot
        build:
            context: . #raiz do projeto
            dockerfile: Dockerfile #Ler o arquivo Dockerfile
        ports:
            - "8081:8081" #Portas externa e interna
        networks:
            - apipedidos-network #Nome da rede compartilhada
        depends_on:
            - postgres #Nome do serviço que iremos aguardar para executar a API
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd_apipedidos
            SPRING_DATASOURCE_USERNAME: usuario_apipedidos
            SPRING_DATASOURCE_PASSWORD: senha_apipedidos

    postgres: # Nome do serviço
        image: postgres:16 # imagem oficial do postgres versão 16
        container_name: api-pedidos-postgresql
        restart: always # sempre reinicie o container quando ele parar
        environment:
            POSTGRES_USER: usuario_apipedidos
            POSTGRES_PASSWORD: senha_apipedidos
            POSTGRES_DB: bd_apipedidos
        ports:
            - "5440:5432" # porta externa para a máquina local / porta interna do container
        volumes:
            - postgres_data:/var/lib/postgresql/data # local dentro do container para armazenar os dados
        networks:
            - apipedidos-network #Nome da rede compartilhada
volumes:
    postgres_data: # Registrando o volume para armazenar os dados

networks:
    apipedidos-network: #Nome da rede
        driver: bridge #Rede Compartilhada